using System;
using System.Collections.Generic;

namespace school.Model
{
    public partial class AggSalesExternal
    {
        public int Budgetjobid { get; set; }
        public int Quarryid { get; set; }
        public int Itemid { get; set; }
        public string Delivery { get; set; }
        public string Quarrydesc { get; set; }
        public string Itemtype { get; set; }
        public string Itemdesc { get; set; }
        public decimal? VolMtp1 { get; set; }
        public decimal? VolJan1 { get; set; }
        public decimal? VolFeb1 { get; set; }
        public decimal? VolMar1 { get; set; }
        public decimal? VolApr1 { get; set; }
        public decimal? VolMay1 { get; set; }
        public decimal? VolJun1 { get; set; }
        public decimal? VolJul1 { get; set; }
        public decimal? VolAug1 { get; set; }
        public decimal? VolSep1 { get; set; }
        public decimal? VolOct1 { get; set; }
        public decimal? VolNov1 { get; set; }
        public decimal? VolDec1 { get; set; }
        public decimal? VolMtp2 { get; set; }
        public decimal? VolJan2 { get; set; }
        public decimal? VolFeb2 { get; set; }
        public decimal? VolMar2 { get; set; }
        public decimal? VolApr2 { get; set; }
        public decimal? VolMay2 { get; set; }
        public decimal? VolJun2 { get; set; }
        public decimal? VolJul2 { get; set; }
        public decimal? VolAug2 { get; set; }
        public decimal? VolSep2 { get; set; }
        public decimal? VolOct2 { get; set; }
        public decimal? VolNov2 { get; set; }
        public decimal? VolDec2 { get; set; }
        public decimal? VolMtp3 { get; set; }
        public decimal? VolJan3 { get; set; }
        public decimal? VolFeb3 { get; set; }
        public decimal? VolMar3 { get; set; }
        public decimal? VolApr3 { get; set; }
        public decimal? VolMay3 { get; set; }
        public decimal? VolJun3 { get; set; }
        public decimal? VolJul3 { get; set; }
        public decimal? VolAug3 { get; set; }
        public decimal? VolSep3 { get; set; }
        public decimal? VolOct3 { get; set; }
        public decimal? VolNov3 { get; set; }
        public decimal? VolDec3 { get; set; }
        public decimal? AspMtp1 { get; set; }
        public decimal? AspJan1 { get; set; }
        public decimal? AspFeb1 { get; set; }
        public decimal? AspMar1 { get; set; }
        public decimal? AspApr1 { get; set; }
        public decimal? AspMay1 { get; set; }
        public decimal? AspJun1 { get; set; }
        public decimal? AspJul1 { get; set; }
        public decimal? AspAug1 { get; set; }
        public decimal? AspSep1 { get; set; }
        public decimal? AspOct1 { get; set; }
        public decimal? AspNov1 { get; set; }
        public decimal? AspDec1 { get; set; }
        public decimal? AspMtp2 { get; set; }
        public decimal? AspJan2 { get; set; }
        public decimal? AspFeb2 { get; set; }
        public decimal? AspMar2 { get; set; }
        public decimal? AspApr2 { get; set; }
        public decimal? AspMay2 { get; set; }
        public decimal? AspJun2 { get; set; }
        public decimal? AspJul2 { get; set; }
        public decimal? AspAug2 { get; set; }
        public decimal? AspSep2 { get; set; }
        public decimal? AspOct2 { get; set; }
        public decimal? AspNov2 { get; set; }
        public decimal? AspDec2 { get; set; }
        public decimal? AspMtp3 { get; set; }
        public decimal? AspJan3 { get; set; }
        public decimal? AspFeb3 { get; set; }
        public decimal? AspMar3 { get; set; }
        public decimal? AspApr3 { get; set; }
        public decimal? AspMay3 { get; set; }
        public decimal? AspJun3 { get; set; }
        public decimal? AspJul3 { get; set; }
        public decimal? AspAug3 { get; set; }
        public decimal? AspSep3 { get; set; }
        public decimal? AspOct3 { get; set; }
        public decimal? AspNov3 { get; set; }
        public decimal? AspDec3 { get; set; }
        public decimal? NetMtp1 { get; set; }
        public decimal? NetJan1 { get; set; }
        public decimal? NetFeb1 { get; set; }
        public decimal? NetMar1 { get; set; }
        public decimal? NetApr1 { get; set; }
        public decimal? NetMay1 { get; set; }
        public decimal? NetJun1 { get; set; }
        public decimal? NetJul1 { get; set; }
        public decimal? NetAug1 { get; set; }
        public decimal? NetSep1 { get; set; }
        public decimal? NetOct1 { get; set; }
        public decimal? NetNov1 { get; set; }
        public decimal? NetDec1 { get; set; }
        public decimal? NetMtp2 { get; set; }
        public decimal? NetJan2 { get; set; }
        public decimal? NetFeb2 { get; set; }
        public decimal? NetMar2 { get; set; }
        public decimal? NetApr2 { get; set; }
        public decimal? NetMay2 { get; set; }
        public decimal? NetJun2 { get; set; }
        public decimal? NetJul2 { get; set; }
        public decimal? NetAug2 { get; set; }
        public decimal? NetSep2 { get; set; }
        public decimal? NetOct2 { get; set; }
        public decimal? NetNov2 { get; set; }
        public decimal? NetDec2 { get; set; }
        public decimal? NetMtp3 { get; set; }
        public decimal? NetJan3 { get; set; }
        public decimal? NetFeb3 { get; set; }
        public decimal? NetMar3 { get; set; }
        public decimal? NetApr3 { get; set; }
        public decimal? NetMay3 { get; set; }
        public decimal? NetJun3 { get; set; }
        public decimal? NetJul3 { get; set; }
        public decimal? NetAug3 { get; set; }
        public decimal? NetSep3 { get; set; }
        public decimal? NetOct3 { get; set; }
        public decimal? NetNov3 { get; set; }
        public decimal? NetDec3 { get; set; }
        public string Createdby { get; set; }
        public DateTime? Createddate { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Modifieddate { get; set; }
        public bool? Isdeleted { get; set; }
    }
}
