using System;
using System.Collections.Generic;

namespace school.Model
{
    public partial class RmxCement
    {
        public int Budgetjobid { get; set; }
        public int Rmxcomponentid { get; set; }
        public string Batchingplantid { get; set; }
        public string Batchingplantdesc { get; set; }
        public string Batchingplanttype { get; set; }
        public string Prodcostcenterid { get; set; }
        public string Distcostcenterid { get; set; }
        public int? Regionid { get; set; }
        public string Regiondesc { get; set; }
        public int? Item0 { get; set; }
        public int? Item1 { get; set; }
        public int? Item2 { get; set; }
        public int? Item3 { get; set; }
        public int? Item4 { get; set; }
        public int? Item5 { get; set; }
        public int? Item6 { get; set; }
        public int? Item7 { get; set; }
        public int? Item8 { get; set; }
        public int? Item9 { get; set; }
        public string Item0Desc { get; set; }
        public string Item1Desc { get; set; }
        public string Item2Desc { get; set; }
        public string Item3Desc { get; set; }
        public string Item4Desc { get; set; }
        public string Item5Desc { get; set; }
        public string Item6Desc { get; set; }
        public string Item7Desc { get; set; }
        public string Item8Desc { get; set; }
        public string Item9Desc { get; set; }
        public decimal? Vol0Mtp1 { get; set; }
        public decimal? Vol0Jan1 { get; set; }
        public decimal? Vol0Feb1 { get; set; }
        public decimal? Vol0Mar1 { get; set; }
        public decimal? Vol0Apr1 { get; set; }
        public decimal? Vol0May1 { get; set; }
        public decimal? Vol0Jun1 { get; set; }
        public decimal? Vol0Jul1 { get; set; }
        public decimal? Vol0Aug1 { get; set; }
        public decimal? Vol0Sep1 { get; set; }
        public decimal? Vol0Oct1 { get; set; }
        public decimal? Vol0Nov1 { get; set; }
        public decimal? Vol0Dec1 { get; set; }
        public decimal? Vol0Mtp2 { get; set; }
        public decimal? Vol0Jan2 { get; set; }
        public decimal? Vol0Feb2 { get; set; }
        public decimal? Vol0Mar2 { get; set; }
        public decimal? Vol0Apr2 { get; set; }
        public decimal? Vol0May2 { get; set; }
        public decimal? Vol0Jun2 { get; set; }
        public decimal? Vol0Jul2 { get; set; }
        public decimal? Vol0Aug2 { get; set; }
        public decimal? Vol0Sep2 { get; set; }
        public decimal? Vol0Oct2 { get; set; }
        public decimal? Vol0Nov2 { get; set; }
        public decimal? Vol0Dec2 { get; set; }
        public decimal? Vol0Mtp3 { get; set; }
        public decimal? Vol0Jan3 { get; set; }
        public decimal? Vol0Feb3 { get; set; }
        public decimal? Vol0Mar3 { get; set; }
        public decimal? Vol0Apr3 { get; set; }
        public decimal? Vol0May3 { get; set; }
        public decimal? Vol0Jun3 { get; set; }
        public decimal? Vol0Jul3 { get; set; }
        public decimal? Vol0Aug3 { get; set; }
        public decimal? Vol0Sep3 { get; set; }
        public decimal? Vol0Oct3 { get; set; }
        public decimal? Vol0Nov3 { get; set; }
        public decimal? Vol0Dec3 { get; set; }
        public decimal? Vol1Mtp1 { get; set; }
        public decimal? Vol1Jan1 { get; set; }
        public decimal? Vol1Feb1 { get; set; }
        public decimal? Vol1Mar1 { get; set; }
        public decimal? Vol1Apr1 { get; set; }
        public decimal? Vol1May1 { get; set; }
        public decimal? Vol1Jun1 { get; set; }
        public decimal? Vol1Jul1 { get; set; }
        public decimal? Vol1Aug1 { get; set; }
        public decimal? Vol1Sep1 { get; set; }
        public decimal? Vol1Oct1 { get; set; }
        public decimal? Vol1Nov1 { get; set; }
        public decimal? Vol1Dec1 { get; set; }
        public decimal? Vol1Mtp2 { get; set; }
        public decimal? Vol1Jan2 { get; set; }
        public decimal? Vol1Feb2 { get; set; }
        public decimal? Vol1Mar2 { get; set; }
        public decimal? Vol1Apr2 { get; set; }
        public decimal? Vol1May2 { get; set; }
        public decimal? Vol1Jun2 { get; set; }
        public decimal? Vol1Jul2 { get; set; }
        public decimal? Vol1Aug2 { get; set; }
        public decimal? Vol1Sep2 { get; set; }
        public decimal? Vol1Oct2 { get; set; }
        public decimal? Vol1Nov2 { get; set; }
        public decimal? Vol1Dec2 { get; set; }
        public decimal? Vol1Mtp3 { get; set; }
        public decimal? Vol1Jan3 { get; set; }
        public decimal? Vol1Feb3 { get; set; }
        public decimal? Vol1Mar3 { get; set; }
        public decimal? Vol1Apr3 { get; set; }
        public decimal? Vol1May3 { get; set; }
        public decimal? Vol1Jun3 { get; set; }
        public decimal? Vol1Jul3 { get; set; }
        public decimal? Vol1Aug3 { get; set; }
        public decimal? Vol1Sep3 { get; set; }
        public decimal? Vol1Oct3 { get; set; }
        public decimal? Vol1Nov3 { get; set; }
        public decimal? Vol1Dec3 { get; set; }
        public decimal? Vol2Mtp1 { get; set; }
        public decimal? Vol2Jan1 { get; set; }
        public decimal? Vol2Feb1 { get; set; }
        public decimal? Vol2Mar1 { get; set; }
        public decimal? Vol2Apr1 { get; set; }
        public decimal? Vol2May1 { get; set; }
        public decimal? Vol2Jun1 { get; set; }
        public decimal? Vol2Jul1 { get; set; }
        public decimal? Vol2Aug1 { get; set; }
        public decimal? Vol2Sep1 { get; set; }
        public decimal? Vol2Oct1 { get; set; }
        public decimal? Vol2Nov1 { get; set; }
        public decimal? Vol2Dec1 { get; set; }
        public decimal? Vol2Mtp2 { get; set; }
        public decimal? Vol2Jan2 { get; set; }
        public decimal? Vol2Feb2 { get; set; }
        public decimal? Vol2Mar2 { get; set; }
        public decimal? Vol2Apr2 { get; set; }
        public decimal? Vol2May2 { get; set; }
        public decimal? Vol2Jun2 { get; set; }
        public decimal? Vol2Jul2 { get; set; }
        public decimal? Vol2Aug2 { get; set; }
        public decimal? Vol2Sep2 { get; set; }
        public decimal? Vol2Oct2 { get; set; }
        public decimal? Vol2Nov2 { get; set; }
        public decimal? Vol2Dec2 { get; set; }
        public decimal? Vol2Mtp3 { get; set; }
        public decimal? Vol2Jan3 { get; set; }
        public decimal? Vol2Feb3 { get; set; }
        public decimal? Vol2Mar3 { get; set; }
        public decimal? Vol2Apr3 { get; set; }
        public decimal? Vol2May3 { get; set; }
        public decimal? Vol2Jun3 { get; set; }
        public decimal? Vol2Jul3 { get; set; }
        public decimal? Vol2Aug3 { get; set; }
        public decimal? Vol2Sep3 { get; set; }
        public decimal? Vol2Oct3 { get; set; }
        public decimal? Vol2Nov3 { get; set; }
        public decimal? Vol2Dec3 { get; set; }
        public decimal? Vol3Mtp1 { get; set; }
        public decimal? Vol3Jan1 { get; set; }
        public decimal? Vol3Feb1 { get; set; }
        public decimal? Vol3Mar1 { get; set; }
        public decimal? Vol3Apr1 { get; set; }
        public decimal? Vol3May1 { get; set; }
        public decimal? Vol3Jun1 { get; set; }
        public decimal? Vol3Jul1 { get; set; }
        public decimal? Vol3Aug1 { get; set; }
        public decimal? Vol3Sep1 { get; set; }
        public decimal? Vol3Oct1 { get; set; }
        public decimal? Vol3Nov1 { get; set; }
        public decimal? Vol3Dec1 { get; set; }
        public decimal? Vol3Mtp2 { get; set; }
        public decimal? Vol3Jan2 { get; set; }
        public decimal? Vol3Feb2 { get; set; }
        public decimal? Vol3Mar2 { get; set; }
        public decimal? Vol3Apr2 { get; set; }
        public decimal? Vol3May2 { get; set; }
        public decimal? Vol3Jun2 { get; set; }
        public decimal? Vol3Jul2 { get; set; }
        public decimal? Vol3Aug2 { get; set; }
        public decimal? Vol3Sep2 { get; set; }
        public decimal? Vol3Oct2 { get; set; }
        public decimal? Vol3Nov2 { get; set; }
        public decimal? Vol3Dec2 { get; set; }
        public decimal? Vol3Mtp3 { get; set; }
        public decimal? Vol3Jan3 { get; set; }
        public decimal? Vol3Feb3 { get; set; }
        public decimal? Vol3Mar3 { get; set; }
        public decimal? Vol3Apr3 { get; set; }
        public decimal? Vol3May3 { get; set; }
        public decimal? Vol3Jun3 { get; set; }
        public decimal? Vol3Jul3 { get; set; }
        public decimal? Vol3Aug3 { get; set; }
        public decimal? Vol3Sep3 { get; set; }
        public decimal? Vol3Oct3 { get; set; }
        public decimal? Vol3Nov3 { get; set; }
        public decimal? Vol3Dec3 { get; set; }
        public decimal? Vol4Mtp1 { get; set; }
        public decimal? Vol4Jan1 { get; set; }
        public decimal? Vol4Feb1 { get; set; }
        public decimal? Vol4Mar1 { get; set; }
        public decimal? Vol4Apr1 { get; set; }
        public decimal? Vol4May1 { get; set; }
        public decimal? Vol4Jun1 { get; set; }
        public decimal? Vol4Jul1 { get; set; }
        public decimal? Vol4Aug1 { get; set; }
        public decimal? Vol4Sep1 { get; set; }
        public decimal? Vol4Oct1 { get; set; }
        public decimal? Vol4Nov1 { get; set; }
        public decimal? Vol4Dec1 { get; set; }
        public decimal? Vol4Mtp2 { get; set; }
        public decimal? Vol4Jan2 { get; set; }
        public decimal? Vol4Feb2 { get; set; }
        public decimal? Vol4Mar2 { get; set; }
        public decimal? Vol4Apr2 { get; set; }
        public decimal? Vol4May2 { get; set; }
        public decimal? Vol4Jun2 { get; set; }
        public decimal? Vol4Jul2 { get; set; }
        public decimal? Vol4Aug2 { get; set; }
        public decimal? Vol4Sep2 { get; set; }
        public decimal? Vol4Oct2 { get; set; }
        public decimal? Vol4Nov2 { get; set; }
        public decimal? Vol4Dec2 { get; set; }
        public decimal? Vol4Mtp3 { get; set; }
        public decimal? Vol4Jan3 { get; set; }
        public decimal? Vol4Feb3 { get; set; }
        public decimal? Vol4Mar3 { get; set; }
        public decimal? Vol4Apr3 { get; set; }
        public decimal? Vol4May3 { get; set; }
        public decimal? Vol4Jun3 { get; set; }
        public decimal? Vol4Jul3 { get; set; }
        public decimal? Vol4Aug3 { get; set; }
        public decimal? Vol4Sep3 { get; set; }
        public decimal? Vol4Oct3 { get; set; }
        public decimal? Vol4Nov3 { get; set; }
        public decimal? Vol4Dec3 { get; set; }
        public decimal? Vol5Mtp1 { get; set; }
        public decimal? Vol5Jan1 { get; set; }
        public decimal? Vol5Feb1 { get; set; }
        public decimal? Vol5Mar1 { get; set; }
        public decimal? Vol5Apr1 { get; set; }
        public decimal? Vol5May1 { get; set; }
        public decimal? Vol5Jun1 { get; set; }
        public decimal? Vol5Jul1 { get; set; }
        public decimal? Vol5Aug1 { get; set; }
        public decimal? Vol5Sep1 { get; set; }
        public decimal? Vol5Oct1 { get; set; }
        public decimal? Vol5Nov1 { get; set; }
        public decimal? Vol5Dec1 { get; set; }
        public decimal? Vol5Mtp2 { get; set; }
        public decimal? Vol5Jan2 { get; set; }
        public decimal? Vol5Feb2 { get; set; }
        public decimal? Vol5Mar2 { get; set; }
        public decimal? Vol5Apr2 { get; set; }
        public decimal? Vol5May2 { get; set; }
        public decimal? Vol5Jun2 { get; set; }
        public decimal? Vol5Jul2 { get; set; }
        public decimal? Vol5Aug2 { get; set; }
        public decimal? Vol5Sep2 { get; set; }
        public decimal? Vol5Oct2 { get; set; }
        public decimal? Vol5Nov2 { get; set; }
        public decimal? Vol5Dec2 { get; set; }
        public decimal? Vol5Mtp3 { get; set; }
        public decimal? Vol5Jan3 { get; set; }
        public decimal? Vol5Feb3 { get; set; }
        public decimal? Vol5Mar3 { get; set; }
        public decimal? Vol5Apr3 { get; set; }
        public decimal? Vol5May3 { get; set; }
        public decimal? Vol5Jun3 { get; set; }
        public decimal? Vol5Jul3 { get; set; }
        public decimal? Vol5Aug3 { get; set; }
        public decimal? Vol5Sep3 { get; set; }
        public decimal? Vol5Oct3 { get; set; }
        public decimal? Vol5Nov3 { get; set; }
        public decimal? Vol5Dec3 { get; set; }
        public decimal? Vol6Mtp1 { get; set; }
        public decimal? Vol6Jan1 { get; set; }
        public decimal? Vol6Feb1 { get; set; }
        public decimal? Vol6Mar1 { get; set; }
        public decimal? Vol6Apr1 { get; set; }
        public decimal? Vol6May1 { get; set; }
        public decimal? Vol6Jun1 { get; set; }
        public decimal? Vol6Jul1 { get; set; }
        public decimal? Vol6Aug1 { get; set; }
        public decimal? Vol6Sep1 { get; set; }
        public decimal? Vol6Oct1 { get; set; }
        public decimal? Vol6Nov1 { get; set; }
        public decimal? Vol6Dec1 { get; set; }
        public decimal? Vol6Mtp2 { get; set; }
        public decimal? Vol6Jan2 { get; set; }
        public decimal? Vol6Feb2 { get; set; }
        public decimal? Vol6Mar2 { get; set; }
        public decimal? Vol6Apr2 { get; set; }
        public decimal? Vol6May2 { get; set; }
        public decimal? Vol6Jun2 { get; set; }
        public decimal? Vol6Jul2 { get; set; }
        public decimal? Vol6Aug2 { get; set; }
        public decimal? Vol6Sep2 { get; set; }
        public decimal? Vol6Oct2 { get; set; }
        public decimal? Vol6Nov2 { get; set; }
        public decimal? Vol6Dec2 { get; set; }
        public decimal? Vol6Mtp3 { get; set; }
        public decimal? Vol6Jan3 { get; set; }
        public decimal? Vol6Feb3 { get; set; }
        public decimal? Vol6Mar3 { get; set; }
        public decimal? Vol6Apr3 { get; set; }
        public decimal? Vol6May3 { get; set; }
        public decimal? Vol6Jun3 { get; set; }
        public decimal? Vol6Jul3 { get; set; }
        public decimal? Vol6Aug3 { get; set; }
        public decimal? Vol6Sep3 { get; set; }
        public decimal? Vol6Oct3 { get; set; }
        public decimal? Vol6Nov3 { get; set; }
        public decimal? Vol6Dec3 { get; set; }
        public decimal? Vol7Mtp1 { get; set; }
        public decimal? Vol7Jan1 { get; set; }
        public decimal? Vol7Feb1 { get; set; }
        public decimal? Vol7Mar1 { get; set; }
        public decimal? Vol7Apr1 { get; set; }
        public decimal? Vol7May1 { get; set; }
        public decimal? Vol7Jun1 { get; set; }
        public decimal? Vol7Jul1 { get; set; }
        public decimal? Vol7Aug1 { get; set; }
        public decimal? Vol7Sep1 { get; set; }
        public decimal? Vol7Oct1 { get; set; }
        public decimal? Vol7Nov1 { get; set; }
        public decimal? Vol7Dec1 { get; set; }
        public decimal? Vol7Mtp2 { get; set; }
        public decimal? Vol7Jan2 { get; set; }
        public decimal? Vol7Feb2 { get; set; }
        public decimal? Vol7Mar2 { get; set; }
        public decimal? Vol7Apr2 { get; set; }
        public decimal? Vol7May2 { get; set; }
        public decimal? Vol7Jun2 { get; set; }
        public decimal? Vol7Jul2 { get; set; }
        public decimal? Vol7Aug2 { get; set; }
        public decimal? Vol7Sep2 { get; set; }
        public decimal? Vol7Oct2 { get; set; }
        public decimal? Vol7Nov2 { get; set; }
        public decimal? Vol7Dec2 { get; set; }
        public decimal? Vol7Mtp3 { get; set; }
        public decimal? Vol7Jan3 { get; set; }
        public decimal? Vol7Feb3 { get; set; }
        public decimal? Vol7Mar3 { get; set; }
        public decimal? Vol7Apr3 { get; set; }
        public decimal? Vol7May3 { get; set; }
        public decimal? Vol7Jun3 { get; set; }
        public decimal? Vol7Jul3 { get; set; }
        public decimal? Vol7Aug3 { get; set; }
        public decimal? Vol7Sep3 { get; set; }
        public decimal? Vol7Oct3 { get; set; }
        public decimal? Vol7Nov3 { get; set; }
        public decimal? Vol7Dec3 { get; set; }
        public decimal? Vol8Mtp1 { get; set; }
        public decimal? Vol8Jan1 { get; set; }
        public decimal? Vol8Feb1 { get; set; }
        public decimal? Vol8Mar1 { get; set; }
        public decimal? Vol8Apr1 { get; set; }
        public decimal? Vol8May1 { get; set; }
        public decimal? Vol8Jun1 { get; set; }
        public decimal? Vol8Jul1 { get; set; }
        public decimal? Vol8Aug1 { get; set; }
        public decimal? Vol8Sep1 { get; set; }
        public decimal? Vol8Oct1 { get; set; }
        public decimal? Vol8Nov1 { get; set; }
        public decimal? Vol8Dec1 { get; set; }
        public decimal? Vol8Mtp2 { get; set; }
        public decimal? Vol8Jan2 { get; set; }
        public decimal? Vol8Feb2 { get; set; }
        public decimal? Vol8Mar2 { get; set; }
        public decimal? Vol8Apr2 { get; set; }
        public decimal? Vol8May2 { get; set; }
        public decimal? Vol8Jun2 { get; set; }
        public decimal? Vol8Jul2 { get; set; }
        public decimal? Vol8Aug2 { get; set; }
        public decimal? Vol8Sep2 { get; set; }
        public decimal? Vol8Oct2 { get; set; }
        public decimal? Vol8Nov2 { get; set; }
        public decimal? Vol8Dec2 { get; set; }
        public decimal? Vol8Mtp3 { get; set; }
        public decimal? Vol8Jan3 { get; set; }
        public decimal? Vol8Feb3 { get; set; }
        public decimal? Vol8Mar3 { get; set; }
        public decimal? Vol8Apr3 { get; set; }
        public decimal? Vol8May3 { get; set; }
        public decimal? Vol8Jun3 { get; set; }
        public decimal? Vol8Jul3 { get; set; }
        public decimal? Vol8Aug3 { get; set; }
        public decimal? Vol8Sep3 { get; set; }
        public decimal? Vol8Oct3 { get; set; }
        public decimal? Vol8Nov3 { get; set; }
        public decimal? Vol8Dec3 { get; set; }
        public decimal? Vol9Mtp1 { get; set; }
        public decimal? Vol9Jan1 { get; set; }
        public decimal? Vol9Feb1 { get; set; }
        public decimal? Vol9Mar1 { get; set; }
        public decimal? Vol9Apr1 { get; set; }
        public decimal? Vol9May1 { get; set; }
        public decimal? Vol9Jun1 { get; set; }
        public decimal? Vol9Jul1 { get; set; }
        public decimal? Vol9Aug1 { get; set; }
        public decimal? Vol9Sep1 { get; set; }
        public decimal? Vol9Oct1 { get; set; }
        public decimal? Vol9Nov1 { get; set; }
        public decimal? Vol9Dec1 { get; set; }
        public decimal? Vol9Mtp2 { get; set; }
        public decimal? Vol9Jan2 { get; set; }
        public decimal? Vol9Feb2 { get; set; }
        public decimal? Vol9Mar2 { get; set; }
        public decimal? Vol9Apr2 { get; set; }
        public decimal? Vol9May2 { get; set; }
        public decimal? Vol9Jun2 { get; set; }
        public decimal? Vol9Jul2 { get; set; }
        public decimal? Vol9Aug2 { get; set; }
        public decimal? Vol9Sep2 { get; set; }
        public decimal? Vol9Oct2 { get; set; }
        public decimal? Vol9Nov2 { get; set; }
        public decimal? Vol9Dec2 { get; set; }
        public decimal? Vol9Mtp3 { get; set; }
        public decimal? Vol9Jan3 { get; set; }
        public decimal? Vol9Feb3 { get; set; }
        public decimal? Vol9Mar3 { get; set; }
        public decimal? Vol9Apr3 { get; set; }
        public decimal? Vol9May3 { get; set; }
        public decimal? Vol9Jun3 { get; set; }
        public decimal? Vol9Jul3 { get; set; }
        public decimal? Vol9Aug3 { get; set; }
        public decimal? Vol9Sep3 { get; set; }
        public decimal? Vol9Oct3 { get; set; }
        public decimal? Vol9Nov3 { get; set; }
        public decimal? Vol9Dec3 { get; set; }
        public string Createdby { get; set; }
        public DateTime? Createddate { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Modifieddate { get; set; }
        public bool? Isdeleted { get; set; }
    }
}
