using System;
using System.Collections.Generic;

namespace school.Model
{
    public partial class RmxDist
    {
        public int Budgetjobid { get; set; }
        public int Transportationtypeid { get; set; }
        public string Owner { get; set; }
        public string Batchingplantid { get; set; }
        public string Transportationtypedesc { get; set; }
        public string Batchingplantdesc { get; set; }
        public string Batchingplanttype { get; set; }
        public string Prodcostcenterid { get; set; }
        public string Distcostcenterid { get; set; }
        public int? Regionid { get; set; }
        public string Regiondesc { get; set; }
        public decimal? Portion { get; set; }
        public decimal? AvgDrumCapacity { get; set; }
        public decimal? LoadSize { get; set; }
        public decimal? AvgFillingDegree { get; set; }
        public decimal? CycleTime { get; set; }
        public decimal? Availability { get; set; }
        public decimal? TripsPerDay { get; set; }
        public decimal? DistanceMtp1 { get; set; }
        public decimal? RateMtp1 { get; set; }
        public decimal? TruckMtp1 { get; set; }
        public decimal? TruckJan1 { get; set; }
        public decimal? TruckFeb1 { get; set; }
        public decimal? TruckMar1 { get; set; }
        public decimal? TruckApr1 { get; set; }
        public decimal? TruckMay1 { get; set; }
        public decimal? TruckJun1 { get; set; }
        public decimal? TruckJul1 { get; set; }
        public decimal? TruckAug1 { get; set; }
        public decimal? TruckSep1 { get; set; }
        public decimal? TruckOct1 { get; set; }
        public decimal? TruckNov1 { get; set; }
        public decimal? TruckDec1 { get; set; }
        public decimal? DistanceMtp2 { get; set; }
        public decimal? RateMtp2 { get; set; }
        public decimal? TruckMtp2 { get; set; }
        public decimal? TruckJan2 { get; set; }
        public decimal? TruckFeb2 { get; set; }
        public decimal? TruckMar2 { get; set; }
        public decimal? TruckApr2 { get; set; }
        public decimal? TruckMay2 { get; set; }
        public decimal? TruckJun2 { get; set; }
        public decimal? TruckJul2 { get; set; }
        public decimal? TruckAug2 { get; set; }
        public decimal? TruckSep2 { get; set; }
        public decimal? TruckOct2 { get; set; }
        public decimal? TruckNov2 { get; set; }
        public decimal? TruckDec2 { get; set; }
        public decimal? DistanceMtp3 { get; set; }
        public decimal? RateMtp3 { get; set; }
        public decimal? TruckMtp3 { get; set; }
        public decimal? TruckJan3 { get; set; }
        public decimal? TruckFeb3 { get; set; }
        public decimal? TruckMar3 { get; set; }
        public decimal? TruckApr3 { get; set; }
        public decimal? TruckMay3 { get; set; }
        public decimal? TruckJun3 { get; set; }
        public decimal? TruckJul3 { get; set; }
        public decimal? TruckAug3 { get; set; }
        public decimal? TruckSep3 { get; set; }
        public decimal? TruckOct3 { get; set; }
        public decimal? TruckNov3 { get; set; }
        public decimal? TruckDec3 { get; set; }
        public decimal? UtilMtp1 { get; set; }
        public decimal? UtilJan1 { get; set; }
        public decimal? UtilFeb1 { get; set; }
        public decimal? UtilMar1 { get; set; }
        public decimal? UtilApr1 { get; set; }
        public decimal? UtilMay1 { get; set; }
        public decimal? UtilJun1 { get; set; }
        public decimal? UtilJul1 { get; set; }
        public decimal? UtilAug1 { get; set; }
        public decimal? UtilSep1 { get; set; }
        public decimal? UtilOct1 { get; set; }
        public decimal? UtilNov1 { get; set; }
        public decimal? UtilDec1 { get; set; }
        public decimal? UtilMtp2 { get; set; }
        public decimal? UtilJan2 { get; set; }
        public decimal? UtilFeb2 { get; set; }
        public decimal? UtilMar2 { get; set; }
        public decimal? UtilApr2 { get; set; }
        public decimal? UtilMay2 { get; set; }
        public decimal? UtilJun2 { get; set; }
        public decimal? UtilJul2 { get; set; }
        public decimal? UtilAug2 { get; set; }
        public decimal? UtilSep2 { get; set; }
        public decimal? UtilOct2 { get; set; }
        public decimal? UtilNov2 { get; set; }
        public decimal? UtilDec2 { get; set; }
        public decimal? UtilMtp3 { get; set; }
        public decimal? UtilJan3 { get; set; }
        public decimal? UtilFeb3 { get; set; }
        public decimal? UtilMar3 { get; set; }
        public decimal? UtilApr3 { get; set; }
        public decimal? UtilMay3 { get; set; }
        public decimal? UtilJun3 { get; set; }
        public decimal? UtilJul3 { get; set; }
        public decimal? UtilAug3 { get; set; }
        public decimal? UtilSep3 { get; set; }
        public decimal? UtilOct3 { get; set; }
        public decimal? UtilNov3 { get; set; }
        public decimal? UtilDec3 { get; set; }
        public string Createdby { get; set; }
        public DateTime? Createddate { get; set; }
        public string Modifiedby { get; set; }
        public DateTime? Modifieddate { get; set; }
        public bool? Isdeleted { get; set; }
        public string Other0 { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string Other4 { get; set; }
        public string Other5 { get; set; }
        public string Other6 { get; set; }
        public string Other7 { get; set; }
        public string Other8 { get; set; }
        public string Other9 { get; set; }
        public string TransportationTypeCostElementId { get; set; }
    }
}
